#!/bin/sh
# Entrypoint: generate the nginx config from config.yaml (web hostname,
# IP-access policy, TLS and docs switches), serve a self-signed placeholder
# until a real certificate exists, run nginx, and hot-reload on certificate or
# config changes.
#
# Hardening notes:
#  - /config/certs is mounted read-only, so a compromised web container cannot
#    replace the certificate the MX serves; the placeholder lives in an
#    image-internal directory instead.
#  - Access logs redact mailbox tokens: the token is a full mailbox credential
#    and would otherwise be written verbatim into every request line.
set -e

# Real certificate (shared with the MX) and the local placeholder fallback.
CERT=/config/certs/cert.pem
KEY=/config/certs/key.pem
PLACEHOLDER_DIR=/etc/nginx/placeholder
PLACEHOLDER_CERT="$PLACEHOLDER_DIR/cert.pem"
PLACEHOLDER_KEY="$PLACEHOLDER_DIR/key.pem"
CONFIG=/config/config.yaml
# Generated by the api container with just the values nginx needs; preferred
# over config.yaml because this container should never hold the DB password.
WEB_CONFIG_FILE=/web-config/web-config.env

USE_PLACEHOLDER="false"
if [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then
  echo "No certificate found in /config/certs - generating a self-signed placeholder"
  mkdir -p "$PLACEHOLDER_DIR"
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$PLACEHOLDER_KEY" -out "$PLACEHOLDER_CERT" -days 3650 \
    -subj "/CN=localhost" >/dev/null 2>&1
  chmod 600 "$PLACEHOLDER_KEY"
  chmod 644 "$PLACEHOLDER_CERT"
  CERT="$PLACEHOLDER_CERT"
  KEY="$PLACEHOLDER_KEY"
  USE_PLACEHOLDER="true"
fi

# HTTP-level directives (rate-limit zones, redacted log format) must live in
# the http context, which is what files under conf.d are included into.
cat > /etc/nginx/conf.d/00-http.conf <<'HTTP_EOF'
# --- access log with mailbox tokens redacted -------------------------------
# Request paths look like /api/v1/<token>/emails/<id>; the token segment is a
# mailbox credential, so it never reaches the log file unchanged.
map $request_uri $redacted_uri {
    "~^(/api/v1/)([A-Za-z0-9_-]{20,})(/.*)$"  $1<token>$3;
    default                                 $request_uri;
}
log_format redacted '$remote_addr - $remote_user [$time_local] '
                    '"$request_method $redacted_uri $server_protocol" $status '
                    '$body_bytes_sent "$http_referer" "$http_user_agent"';
# The access_log itself is set per server block: a directive at http level would
# be inherited *in addition to* the base image's unredacted one, writing every
# request twice (once with the raw mailbox token).

# --- edge rate limiting ----------------------------------------------------
limit_req_zone $binary_remote_addr zone=api_general:10m rate=120r/m;
limit_req_zone $binary_remote_addr zone=api_strict:10m  rate=30r/m;

server_tokens off;

# Per-request error lines ("connect() failed ... request: GET /api/v1/<token>/...")
# would print mailbox tokens, and error_log has no redaction format. Only
# critical conditions are logged here; request outcomes stay visible as status
# codes in the redacted access log above.
error_log /var/log/nginx/error.log crit;
HTTP_EOF

LAST_WEB_HOSTNAME=""
LAST_ALLOW_IP="true"
LAST_TLS="false"
LAST_DOCS="true"

read_web_config() {
  WEB_HOSTNAME=""
  ALLOW_IP="true"
  TLS_ENABLED="false"
  DOCS_ENABLED="true"

  # Preferred source: the generated KEY=value file (no secrets).
  if [ -f "$WEB_CONFIG_FILE" ]; then
    # shellcheck disable=SC1090
    . "$WEB_CONFIG_FILE"
  elif [ -f "$CONFIG" ]; then
    WEB_HOSTNAME=$(sed -n '/^web:/,/^[a-zA-Z]/p' "$CONFIG" | grep -E '^[[:space:]]+hostname:' | head -1 | awk '{print $2}' | tr -d '"' | tr -d "'")
    ALLOW_IP=$(sed -n '/^web:/,/^[a-zA-Z]/p' "$CONFIG" | grep -E '^[[:space:]]+allow_ip_access:' | head -1 | awk '{print $2}' | tr -d '"' | tr -d "'")
    TLS_ENABLED=$(sed -n '/^tls:/,/^[a-zA-Z]/p' "$CONFIG" | grep -E '^[[:space:]]+enabled:' | head -1 | awk '{print $2}' | tr -d '"' | tr -d "'")
    DOCS_ENABLED=$(sed -n '/^server:/,/^[a-zA-Z]/p' "$CONFIG" | grep -E '^[[:space:]]+docs_enabled:' | head -1 | awk '{print $2}' | tr -d '"' | tr -d "'")
  fi
  # 防护：配置写入瞬间可能读到残缺值，非法则沿用上次有效值
  case "$WEB_HOSTNAME" in
    *[!a-zA-Z0-9.-]*) WEB_HOSTNAME="$LAST_WEB_HOSTNAME" ;;
  esac
  [ "$ALLOW_IP" = "true" ] || [ "$ALLOW_IP" = "false" ] || ALLOW_IP="$LAST_ALLOW_IP"
  [ "$TLS_ENABLED" = "true" ] || [ "$TLS_ENABLED" = "false" ] || TLS_ENABLED="$LAST_TLS"
  [ "$DOCS_ENABLED" = "true" ] || [ "$DOCS_ENABLED" = "false" ] || DOCS_ENABLED="$LAST_DOCS"
  LAST_WEB_HOSTNAME="$WEB_HOSTNAME"
  LAST_ALLOW_IP="$ALLOW_IP"
  LAST_TLS="$TLS_ENABLED"
  LAST_DOCS="$DOCS_ENABLED"
}

# Security headers shared by every server block. HSTS is only emitted when a
# real certificate is in use: sending it while a self-signed placeholder is
# served would pin users to a certificate their browser rejects.
# Security headers live in their own file: nginx drops inherited add_header
# directives as soon as a nested level defines one of its own, so every
# location that sets Cache-Control has to include this file explicitly.
build_security_headers() {
  {
    echo 'add_header X-Content-Type-Options "nosniff" always;'
    echo 'add_header X-Frame-Options "DENY" always;'
    echo 'add_header Referrer-Policy "strict-origin-when-cross-origin" always;'
    echo 'add_header Content-Security-Policy "default-src '"'"'self'"'"'; script-src '"'"'self'"'"' '"'"'unsafe-inline'"'"'; style-src '"'"'self'"'"' '"'"'unsafe-inline'"'"'; img-src '"'"'self'"'"' data: https:; font-src '"'"'self'"'"' data:; connect-src '"'"'self'"'"'; frame-src '"'"'self'"'"' data:; frame-ancestors '"'"'none'"'"'; base-uri '"'"'self'"'"'; form-action '"'"'self'"'"'; object-src '"'"'none'"'"'" always;'
    if [ "$USE_PLACEHOLDER" = "false" ]; then
      echo 'add_header Strict-Transport-Security "max-age=31536000" always;'
    fi
  } > /etc/nginx/security-headers.conf
}

write_security_headers() {
  cat >> /etc/nginx/conf.d/default.conf <<'LOG_EOF'
    access_log /var/log/nginx/access.log redacted;
    include /etc/nginx/security-headers.conf;
LOG_EOF
}

# HTTP -> HTTPS redirect when TLS is enabled; the ACME challenge path must
# stay reachable over plain HTTP or renewals break.
write_http_redirect() {
  if [ "$TLS_ENABLED" = "true" ]; then
    cat >> /etc/nginx/conf.d/default.conf <<'REDIR_EOF'
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }
    location / { return 301 https://$host$request_uri; }
REDIR_EOF
    return 0
  fi
  return 1
}

generate_conf() {
  read_web_config
  SERVER_NAME="$WEB_HOSTNAME"
  [ -z "$SERVER_NAME" ] && SERVER_NAME="_"

  # 主服务：正式域名
  cat > /etc/nginx/conf.d/default.conf <<'MAIN_EOF'
server {
    listen 80;
    server_name @SERVER_NAME@;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
MAIN_EOF
  if ! write_http_redirect; then
    cat >> /etc/nginx/conf.d/default.conf <<'MAINPLAIN_EOF'
    include /etc/nginx/locations.conf;
    error_page 404 /404.html;
MAINPLAIN_EOF
  fi
  cat >> /etc/nginx/conf.d/default.conf <<'MAIN2_EOF'
}
server {
    listen 443 ssl;
    server_name @SERVER_NAME@;
    root /usr/share/nginx/html;
    index index.html;
    ssl_certificate @CERT@;
    ssl_certificate_key @KEY@;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
MAIN2_EOF
  write_security_headers
  cat >> /etc/nginx/conf.d/default.conf <<'MAIN3_EOF'
    include /etc/nginx/locations.conf;
    error_page 404 /404.html;
}
MAIN3_EOF

  # 兜底服务：IP / 其他域名
  cat >> /etc/nginx/conf.d/default.conf <<'CATCH_EOF'
server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    ssl_certificate @CERT@;
    ssl_certificate_key @KEY@;
    ssl_protocols TLSv1.2 TLSv1.3;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
CATCH_EOF
  write_security_headers

  if [ "$TLS_ENABLED" = "true" ]; then
    echo '    if ($scheme = http) { return 301 https://$host$request_uri; }' >> /etc/nginx/conf.d/default.conf
  fi

  if [ -n "$WEB_HOSTNAME" ] && [ "$ALLOW_IP" != "true" ]; then
    # 限制模式：仅后台 / API / 证书验证路径可用，其余重定向到正式域名
    cat >> /etc/nginx/conf.d/default.conf <<'LIMIT_EOF'
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }
    # API-key creation path: no edge limit (same reasoning as locations.conf).
    location ^~ /api/v1/api/ {
        include /etc/nginx/security-headers.conf;
        add_header Cache-Control "no-store" always;
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/ {
        limit_req zone=api_general burst=120 nodelay;
        limit_req_status 429;
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /api { try_files /api.html =404; }
    location = /api/ { return 301 /api; }
    location ^~ /admin { try_files $uri $uri.html $uri/index.html =404; }
    location = /setup { try_files /setup.html =404; }
    location /_next/static/ {
        include /etc/nginx/security-headers.conf;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files $uri =404;
    }
    location /_next/ { try_files $uri =404; }
    location / { return 302 https://@WEB_HOSTNAME@$request_uri; }
LIMIT_EOF
    if [ "$DOCS_ENABLED" = "true" ]; then
      cat >> /etc/nginx/conf.d/default.conf <<'LIMITDOCS_EOF'
    location /docs {
        proxy_pass http://api:8000/docs;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /redoc {
        proxy_pass http://api:8000/redoc;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /openapi.json {
        proxy_pass http://api:8000/openapi.json;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
LIMITDOCS_EOF
    fi
  else
    if [ "$DOCS_ENABLED" = "true" ]; then
      cat >> /etc/nginx/conf.d/default.conf <<'FULL_EOF'
    include /etc/nginx/locations.conf;
    error_page 404 /404.html;
FULL_EOF
    else
      # docs_enabled: false - the same surface without the Swagger, ReDoc and
      # OpenAPI proxy locations.
      cat >> /etc/nginx/conf.d/default.conf <<'NODOCS_EOF'
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }
    location = /api { try_files /api.html =404; }
    location = /api/ { return 301 /api; }
    # API-key creation path: no edge limit (same reasoning as locations.conf).
    location ^~ /api/v1/api/ {
        include /etc/nginx/security-headers.conf;
        add_header Cache-Control "no-store" always;
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/ {
        limit_req zone=api_general burst=120 nodelay;
        limit_req_status 429;
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /_next/static/ {
        include /etc/nginx/security-headers.conf;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files $uri =404;
    }
    location / {
        include /etc/nginx/security-headers.conf;
        add_header Cache-Control "no-cache" always;
        rewrite ^(.+)/$ $1 permanent;
        try_files $uri $uri.html $uri/index.html =404;
    }
NODOCS_EOF
    fi
  fi
  echo "}" >> /etc/nginx/conf.d/default.conf

  sed -i "s|@SERVER_NAME@|$SERVER_NAME|g; s|@WEB_HOSTNAME@|$WEB_HOSTNAME|g; s|@CERT@|$CERT|g; s|@KEY@|$KEY|g" /etc/nginx/conf.d/default.conf
}

build_security_headers
generate_conf
nginx

# 监控证书与配置变化并热重载
last_cert=$(stat -c %Y "$CERT" 2>/dev/null || echo 0)
last_key=$(stat -c %Y "$KEY" 2>/dev/null || echo 0)
last_conf=$(stat -c %Y "$WEB_CONFIG_FILE" 2>/dev/null || stat -c %Y "$CONFIG" 2>/dev/null || echo 0)
while true; do
  sleep 20
  now_cert=$(stat -c %Y "$CERT" 2>/dev/null || echo "$last_cert")
  now_key=$(stat -c %Y "$KEY" 2>/dev/null || echo "$last_key")
  now_conf=$(stat -c %Y "$WEB_CONFIG_FILE" 2>/dev/null || stat -c %Y "$CONFIG" 2>/dev/null || echo "$last_conf")

  if [ "$now_cert" != "$last_cert" ] || [ "$now_key" != "$last_key" ]; then
    echo "Certificate changed - reloading nginx"
    nginx -s reload
    last_cert=$now_cert
    last_key=$now_key
  fi

  if [ "$now_conf" != "$last_conf" ]; then
    echo "web configuration changed - regenerating nginx config"
    if generate_conf && nginx -t >/dev/null 2>&1; then
      nginx -s reload
      last_conf=$now_conf
      echo "nginx config regenerated and reloaded"
    else
      echo "nginx config generation failed - keeping previous config"
    fi
  fi
done
